version: "2"
services:
  worker1:
    image: mramos490/regulome:test1
    volumes:
      - /Volumes/CHIMUEL/IRB/isletregulome_shiny/static_data/:/home/docker/tools/isletregulome_shiny/static_data/
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}/{{.ImageName}}/{{.ID}};"
    restart: on-failure
    mem_limit: 1G
    networks:
      - regulome
  worker2:
    image: mramos490/regulome:test1
    volumes:
      - /Volumes/CHIMUEL/IRB/isletregulome_shiny/static_data/:/home/docker/tools/isletregulomebrowser_shiny/static_data/
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}/{{.ImageName}}/{{.ID}};"
    restart: on-failure
    mem_limit: 1G
    networks:
      - regulome
  web:
    image: nginx:1.13
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}/{{.ImageName}}/{{.ID}};"
    ports:
      - "80:80"
    depends_on:
      - "worker1"
      - "worker2"
    restart: on-failure
    networks:
      - regulome
networks:
  regulome:
    driver: bridge
#    config:
#      - subnet: 172.20.0.0/24
#      - ip_range: 172.20.0.0/24
