version: "3"
services:
  worker:
    image: registry.imppc.local:443/regulome:latest
    volumes:
      - /var/lib/docker/volumes/regulome-data/_data:/home/docker/tools/isletregulomebrowser_shiny/static_data/RData/:ro
    #restart: on-failure
    deploy:
#      placement:
#        constraints:  [node.role == manager]
      mode: replicated
      replicas: 4
#      resources:
#        limits:
#          cpus: "0.2" # for a 5 core node and replica 4 that gives up to 1 core each replica
#          memory: 1024M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - regunet
  web:
    image: nginx:1.13
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - "worker"
    deploy:
#      placement:
#        constraints:  [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - regunet
networks:
  regunet:
    driver: bridge
    external: true
#    config:
#      - subnet: 172.20.0.0/24
#      - ip_range: 172.20.0.0/24
