proxy:
  title: Islet Regulome Browser
  hide-navbar: true
  landing-page: /app/isletregulome/
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: none
  container-wait-time: 90000
  container-log-path: ./container-logs
  # Docker configuration
  docker:
#    url: http://127.0.0.1:2375
#    port-range-start: 20000
    internal-networking: true
  specs:
  - id: isletregulome 
    display-name: Islet Regulome Browser
    container-cmd: ["R", "-e", "shiny::runApp('/root/regulome/isletregulome_shiny',  host='0.0.0.0', port = 3838)"]
    container-image: irb-nodata
    container-volumes: [ "/home/mramos/Projects/IRB/IRB_database:/root/regulome/isletregulome_shiny/IRB_database" ]
    container-network: pirb-net

logging:
  file:
    shinyproxy.log
