proxy:
  title: Islet Regulome Browser
  hide-navbar: true
  landing-page: /app/isletregulome/
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: none
  container-wait-time: 90000
  container-log-path: ./logs/container-logs
  docker:
    internal-networking: true
  specs:
  - id: isletregulome 
    display-name: Islet Regulome Browser
    container-cmd: ["R", "-e", "shiny::runApp('/root/regulome/isletregulome_shiny',  host='0.0.0.0', port = 3838)"]
    container-image: pirb-nodata
    container-volumes: [ "/root/PIRB_database:/root/regulome/isletregulome_shiny/PIRB_database" ]
    container-network: pirb-net

logging:
  file:
    logs/shinyproxy.log
