FROM regulomedeps:bioc3.7 as intermediate

# For reference: https://vsupalov.com/build-docker-image-clone-private-repo-ssh-key/
LABEL version="Regulome"
LABEL description="Running regulome app under docker"
# this docker container shouldn't need to install anything but the data from the git repository


#USER root

#RUN apt-get update && apt-get install -y git

USER docker
WORKDIR /home/docker/
ARG SSH_PRIVATE_KEY
RUN mkdir .ssh
RUN ssh-keyscan dogbert.imppc.local >> /home/docker/.ssh/known_hosts

RUN echo "${SSH_PRIVATE_KEY}" > /home/docker/.ssh/id_rsa  && chmod 600 /home/docker/.ssh/id_rsa

RUN git clone git@dogbert.imppc.local:mramos/plotregulome.git \
  && git clone git@dogbert.imppc.local:mramos/isletregulome_shiny.git

#RUN git clone git@dogbert.imppc.local:mramos/isletregulome_shiny.git


FROM regulomedeps:bioc3.7


RUN mkdir -p /home/docker/tools

#ADD install_rpackages.R /tmp/
#RUN R -f /tmp/install_rpackages.R && rm -f /tmp/install_rpackages.R
# new way of installing plotregulome
COPY --from=intermediate /home/docker/plotregulome /home/docker/tools/plotRegulome
#WORKDIR /home/docker/tools/plotRegulome
#RUN R -e 'devtools::install()'

WORKDIR /home/docker/tools
USER root
RUN chown -R docker /home/docker
RUN R CMD INSTALL plotRegulome

#USER docker


COPY --from=intermediate /home/docker/isletregulome_shiny /home/docker/tools/isletregulomebrowser_shiny
USER root
RUN chown -R docker /home/docker
USER docker
RUN mkdir /home/docker/tools/isletregulomebrowser_shiny/static_data
WORKDIR /home/docker/tools/isletregulomebrowser_shiny/static_data
RUN wget http://locke.imppc.local/groups/lplab/regulome-data.tar && \
  echo "dd1d7d51fdba4c4a74785ba72f0af8ba  regulome-data.tar" > regulome-data.tar.md5 \
  md5sum -c regulome-data.tar.md5 && \
  tar xf regulome-data.tar && \
  rm -f regulome-data.tar && \
  rm -f regulome-data.tar.md5
  

WORKDIR /home/docker/tools/isletregulomebrowser_shiny

  
CMD ["R", "-f", "runIsletRegulome.R"]
