proxy:
  title: Islet Regulome Browser
  hide-navbar: true
  landing-page: /app/isletregulome/
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: none
  container-wait-time: 90000
  container-log-path: ./container-logs
  docker:
    url: http://localhost:2375
    port-range-start: 20000
  specs:
  - id: isletregulome 
    display-name: Islet Regulome Browser
    container-image: pirb-nodata
    container-volumes: [ "/home/regulome/PIRB_database:/root/regulome/isletregulome_shiny/PIRB_database" ]
    container-network: pirb-net

logging:
  file:
    shinyproxy.log
